name: optimize
on: [push]
jobs:
  optimize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install oxipng
        uses: baptiste0928/cargo-install@v2
        with:
          crate: oxipng
          version: latest
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          since_last_remote_commit: "true"
          files: |
            **/*.png
      - name: Run oxipng
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          oxipng -o 3 -i 0 --strip safe ${{ steps.changed-files.outputs.all_changed_files }}
      - name: Get modified files
        id: modified-files
        run: echo "::set-output name=all_modified_files::$(git status --porcelain | sed s/^...// | sed -z 's/\n/%0A/g;s/%0A$/\n/')"
      - name: Commit and push changes
        if: ${{ steps.modified-files.outputs.all_modified_files }}
        uses: swinton/commit@v2.x
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ${{ steps.modified-files.outputs.all_modified_files }}
          commit-message: "Automatically reformatted code!"
          ref: ${{ github.ref }}
